version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${NAME}:local
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules/
    ports:
      - ${PORT}:${PORT}
